site_name: Professional Demos
site_description: Playable demos for QA automation, CRO experimentation, search analytics, and project delivery.
repo_url: https://github.com/cgranjaobando/professional-demos
nav:
  - Start Here: index.md
  - QA Automation:
      - Swag Labs Playwright: qa.md
  - CRO Experimentation: cro.md
  - Search Evaluation: search.md
  - Delivery Playbook: pm.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    - toc.follow
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
