name: CI

on:
  push:
    branches: ["main"]
  pull_request:

defaults:
  run:
    working-directory: professional-demos

env:
  PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r demos/search/ranking-metrics-notebook/requirements.txt
          python -m pip install -r demos/qa/swaglabs-playwright/api/requirements.txt

      - name: Run Playwright tests (headless)
        run: npm run ci:headless

      - name: Run accessibility-only suite
        run: npm run a11y

      - name: Generate ranking metrics summary
        run: python demos/search/ranking-metrics-notebook/calc_metrics.py --output demos/search/ranking-metrics-notebook/outputs/metrics_summary.csv

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: professional-demos/playwright-report
          retention-days: 7

      - name: Upload test results (traces, axe reports)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: professional-demos/test-results
          retention-days: 7

      - name: Upload ranking metrics summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ranking-metrics
          path: professional-demos/demos/search/ranking-metrics-notebook/outputs/metrics_summary.csv
          retention-days: 7
